DALO_LIBRARY_ABI=1
DALO_LIBRARY_NAME="compiler-linker"
DALO_LIBRARY_VERSION="1.0.0"
DALO_LIBRARY_REQUIRES="compiler-ir compiler-definitions compiler-connect compiler-features"

[ "${DALO_COMPILER_LINKER_INCLUDE:-0}" -eq 0 ] || return 0
DALO_COMPILER_LINKER_INCLUDE=1

# v1 emitter deliberately emits canonical project metadata/IR and a runtime
# bootstrap. Feature-selected runtime extraction is the next lowering stage.
dalo_link_machine(){
 [ $# -eq 3 ] || return 2
 local root="$1"
 local p="$2"
 local out="$3"
 local nv="${p}_NAME"
 local vv="${p}_VERSION"
 local o
 local -n objs="${p}_OBJECTS"
 local -n types="${p}_OBJECT_TYPE"
 local -n edges="${p}_EDGES"
 local -n features="${p}_FEATURES"
 {
   printf '#!/usr/bin/env bash\n'
   printf '# Generated by DALO compiler. Do not edit.\n'
   printf 'DALO_MACHINE_ABI=1\n'
   printf 'DALO_PROJECT_NAME=%q\n' "${!nv}"
   printf 'DALO_PROJECT_VERSION=%q\n' "${!vv}"
   printf 'DALO_MACHINE_OBJECTS=('
   for o in "${objs[@]}"; do printf ' %q' "$o"; done
   printf ' )\n'
   for o in "${objs[@]}"; do printf 'DALO_MACHINE_OBJECT_TYPE_%s=%q\n' "$o" "${types[$o]}"; done
   printf 'dalo_machine_describe() {\n'
   printf '  printf "PROJECT\\t%%s\\t%%s\\n" "$DALO_PROJECT_NAME" "$DALO_PROJECT_VERSION"\n'
   for o in "${objs[@]}"; do
     printf '  printf "OBJECT\\t%%s\\t%%s\\n" %q %q\n' "$o" "${types[$o]}"
   done
   local edge so sp do_ dp
   for edge in "${edges[@]}"; do
     IFS=$'\t' read -r so sp do_ dp <<<"$edge"
     printf '  printf "EDGE\\t%%s.%%s\\t%%s.%%s\\n" %q %q %q %q\n' "$so" "$sp" "$do_" "$dp"
   done
   local feature
   for feature in "${features[@]}"; do
     printf '  printf "FEATURE\\t%%s\\n" %q\n' "$feature"
   done
   printf '}\n'
   printf 'case "${1:-}" in --describe) dalo_machine_describe ;; "") : ;; *) printf "unknown MACHINE option: %%s\\n" "$1" >&2; exit 2;; esac\n'
 } >"$out" || return
 chmod +x "$out"
 bash -n "$out"
}
